import type { EnergyMeasureSeed, MeasurePriceMapSeed, PriceItemSeed, PriceSourceSeed } from './types';

export const priceSources: PriceSourceSeed[] = [
  {
    name: 'ANCLORA_INTERNAL_COST_SEED_2026_05',
    providerType: 'INTERNAL_SEED',
    sourceKind: 'INTERNAL',
    versionLabel: '2026.05',
    region: 'ES',
    reliability: 'MEDIUM',
    capturedAt: '2026-05-10',
    notes: 'Catálogo interno inicial con rangos prudentes para estimaciones orientativas EnergyScan.',
  },
  {
    name: 'MARKET_REFORM_REFERENCE_2026_05',
    providerType: 'MARKET_REFERENCE',
    sourceKind: 'MARKET_GUIDE',
    versionLabel: '2026.05',
    region: 'ES',
    reliability: 'LOW',
    capturedAt: '2026-05-10',
    notes: 'Referencias de mercado normalizadas para reforma y rehabilitación. No sustituye base técnica oficial.',
  },
  {
    name: 'TECHNICAL_PRICE_DATABASE_PLACEHOLDER',
    providerType: 'TECHNICAL_PRIVATE',
    sourceKind: 'PRICE_DATABASE',
    versionLabel: 'roadmap',
    region: 'ES',
    reliability: 'HIGH',
    notes: 'Placeholder para BEDEC/CYPE/PREOC/IVE/BCCA normalizados en futuras ingestas.',
  },
];

export const priceItems: PriceItemSeed[] = [
  { guid: 'price-env-windows-double-glazing-m2', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'ENV_WINDOWS_DOUBLE_GLAZING_M2', title: 'Ventana eficiente con doble acristalamiento bajo emisivo', unit: 'm2', minUnitPrice: 280, midUnitPrice: 420, maxUnitPrice: 650, category: 'ENVELOPE', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['windows', 'envelope'], confidence: 'MEDIUM' },
  { guid: 'price-env-roof-insulation-m2', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'ENV_ROOF_INSULATION_M2', title: 'Aislamiento térmico de cubierta', unit: 'm2', minUnitPrice: 90, midUnitPrice: 135, maxUnitPrice: 180, category: 'ENVELOPE', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['roof', 'insulation'], confidence: 'MEDIUM' },
  { guid: 'price-env-facade-insulation-m2', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'ENV_FACADE_INSULATION_M2', title: 'Aislamiento de fachada / SATE / trasdosado', unit: 'm2', minUnitPrice: 100, midUnitPrice: 220, maxUnitPrice: 400, category: 'ENVELOPE', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['facade', 'insulation'], confidence: 'MEDIUM' },
  { guid: 'price-env-terrace-waterproofing-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'ENV_TERRACE_WATERPROOFING_M2', title: 'Impermeabilización y mejora básica de terraza', unit: 'm2', minUnitPrice: 15, midUnitPrice: 40, maxUnitPrice: 80, category: 'TERRACE', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['terrace'], confidence: 'LOW' },
  { guid: 'price-hvac-heat-pump-air-air-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'HVAC_HEAT_PUMP_AIR_AIR_UNIT', title: 'Bomba de calor aire-aire / splits eficientes', unit: 'ud', minUnitPrice: 2500, midUnitPrice: 4500, maxUnitPrice: 7500, category: 'HVAC', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['heat_pump', 'air_air'], confidence: 'MEDIUM' },
  { guid: 'price-hvac-heat-pump-air-water-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'HVAC_HEAT_PUMP_AIR_WATER_UNIT', title: 'Aerotermia aire-agua para climatización/ACS', unit: 'ud', minUnitPrice: 8000, midUnitPrice: 12500, maxUnitPrice: 19000, category: 'HVAC', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['heat_pump', 'air_water', 'acs'], confidence: 'MEDIUM' },
  { guid: 'price-hvac-heat-pump-geothermal-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'HVAC_HEAT_PUMP_GEOTHERMAL_UNIT', title: 'Bomba de calor geotérmica', unit: 'ud', minUnitPrice: 18000, midUnitPrice: 28000, maxUnitPrice: 45000, category: 'HVAC', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['heat_pump', 'geothermal'], confidence: 'LOW' },
  { guid: 'price-hvac-hybrid-heat-pump-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'HVAC_HYBRID_HEAT_PUMP_UNIT', title: 'Sistema híbrido bomba de calor + apoyo existente', unit: 'ud', minUnitPrice: 6500, midUnitPrice: 9500, maxUnitPrice: 15000, category: 'HVAC', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA'], tags: ['heat_pump', 'hybrid'], confidence: 'LOW' },
  { guid: 'price-ren-pv-basic-kwp', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'REN_PV_BASIC_KWP', title: 'Instalación fotovoltaica de autoconsumo', unit: 'kWp', minUnitPrice: 1100, midUnitPrice: 1500, maxUnitPrice: 2100, category: 'RENEWABLE', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY', 'LOCAL'], tags: ['pv', 'renewable'], confidence: 'MEDIUM' },
  { guid: 'price-ren-solar-thermal-acs-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'REN_SOLAR_THERMAL_ACS_UNIT', title: 'Solar térmica para ACS', unit: 'ud', minUnitPrice: 2500, midUnitPrice: 4200, maxUnitPrice: 7500, category: 'ACS', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['solar_thermal', 'acs'], confidence: 'LOW' },
  { guid: 'price-vent-heat-recovery-unit', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'VENT_HEAT_RECOVERY_UNIT', title: 'Ventilación mecánica con recuperación de calor', unit: 'ud', minUnitPrice: 3500, midUnitPrice: 6500, maxUnitPrice: 12000, category: 'VENTILATION', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['ventilation', 'heat_recovery'], confidence: 'LOW' },
  { guid: 'price-elec-renewal-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'ELEC_RENEWAL_M2', title: 'Renovación eléctrica orientativa', unit: 'm2', minUnitPrice: 15, midUnitPrice: 28, maxUnitPrice: 40, category: 'ELECTRICAL', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['electrical'], confidence: 'MEDIUM' },
  { guid: 'price-plumbing-renewal-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'PLUMBING_RENEWAL_M2', title: 'Renovación de fontanería orientativa', unit: 'm2', minUnitPrice: 20, midUnitPrice: 35, maxUnitPrice: 50, category: 'PLUMBING', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['plumbing'], confidence: 'MEDIUM' },
  { guid: 'price-bath-basic-unit', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'BATHROOM_REFORM_BASIC_UNIT', title: 'Reforma básica de baño eficiente', unit: 'ud', minUnitPrice: 3500, midUnitPrice: 4000, maxUnitPrice: 4500, category: 'BATHROOM', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL'], tags: ['bathroom'], confidence: 'MEDIUM' },
  { guid: 'price-bath-medium-unit', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'BATHROOM_REFORM_MEDIUM_UNIT', title: 'Reforma media de baño eficiente', unit: 'ud', minUnitPrice: 5000, midUnitPrice: 6000, maxUnitPrice: 7000, category: 'BATHROOM', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA'], tags: ['bathroom'], confidence: 'MEDIUM' },
  { guid: 'price-bath-premium-unit', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'BATHROOM_REFORM_PREMIUM_UNIT', title: 'Reforma premium de baño eficiente', unit: 'ud', minUnitPrice: 8000, midUnitPrice: 11000, maxUnitPrice: 15000, category: 'BATHROOM', applicableTo: ['SINGLE_FAMILY', 'VILLA'], tags: ['bathroom'], confidence: 'LOW' },
  { guid: 'price-local-simple-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'LOCAL_REFORM_SIMPLE_M2', title: 'Reforma simple de local comercial', unit: 'm2', minUnitPrice: 300, midUnitPrice: 500, maxUnitPrice: 700, category: 'LOCAL', applicableTo: ['LOCAL'], tags: ['local'], confidence: 'MEDIUM' },
  { guid: 'price-local-full-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'LOCAL_REFORM_FULL_M2', title: 'Acondicionamiento completo de local', unit: 'm2', minUnitPrice: 600, midUnitPrice: 900, maxUnitPrice: 1200, category: 'LOCAL', applicableTo: ['LOCAL'], tags: ['local'], confidence: 'MEDIUM' },
  { guid: 'price-community-facade-m2', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'COMMUNITY_FACADE_REHAB_M2', title: 'Rehabilitación de fachada comunitaria', unit: 'm2', minUnitPrice: 100, midUnitPrice: 240, maxUnitPrice: 400, category: 'COMMUNITY', applicableTo: ['COMMUNITY'], tags: ['community', 'facade'], confidence: 'MEDIUM' },
  { guid: 'price-community-roof-m2', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'COMMUNITY_ROOF_REHAB_M2', title: 'Rehabilitación de cubierta comunitaria', unit: 'm2', minUnitPrice: 90, midUnitPrice: 135, maxUnitPrice: 180, category: 'COMMUNITY', applicableTo: ['COMMUNITY'], tags: ['community', 'roof'], confidence: 'MEDIUM' },
  { guid: 'price-deep-basic-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'DEEP_RETROFIT_BASIC_M2', title: 'Rehabilitación energética integral básica', unit: 'm2', minUnitPrice: 400, midUnitPrice: 500, maxUnitPrice: 600, category: 'OTHER', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA'], tags: ['deep_retrofit'], confidence: 'LOW' },
  { guid: 'price-deep-medium-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'DEEP_RETROFIT_MEDIUM_M2', title: 'Rehabilitación energética integral media', unit: 'm2', minUnitPrice: 600, midUnitPrice: 750, maxUnitPrice: 900, category: 'OTHER', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA'], tags: ['deep_retrofit'], confidence: 'LOW' },
  { guid: 'price-deep-premium-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'DEEP_RETROFIT_PREMIUM_M2', title: 'Rehabilitación energética integral premium', unit: 'm2', minUnitPrice: 900, midUnitPrice: 1050, maxUnitPrice: 1200, category: 'OTHER', applicableTo: ['VILLA'], tags: ['deep_retrofit'], confidence: 'LOW' },
  { guid: 'price-structural-rehab-m2', sourceName: 'MARKET_REFORM_REFERENCE_2026_05', code: 'STRUCTURAL_REHAB_M2', title: 'Rehabilitación estructural/profunda compleja', unit: 'm2', minUnitPrice: 1400, midUnitPrice: 1600, maxUnitPrice: 1800, category: 'STRUCTURE', applicableTo: ['SINGLE_FAMILY', 'VILLA', 'COMMUNITY'], tags: ['structure'], confidence: 'LOW' },
  { guid: 'price-contingency-percent', sourceName: 'ANCLORA_INTERNAL_COST_SEED_2026_05', code: 'CONTINGENCY_PERCENT', title: 'Contingencia orientativa', unit: 'percent', minUnitPrice: 8, midUnitPrice: 10, maxUnitPrice: 12, category: 'OTHER', applicableTo: ['FLAT', 'SINGLE_FAMILY', 'VILLA', 'LOCAL', 'COMMUNITY'], tags: ['contingency'], confidence: 'MEDIUM' },
];

export const energyMeasures: EnergyMeasureSeed[] = [
  { guid: 'measure-replace-windows', code: 'replace_windows', title: 'Sustituir ventanas', category: 'ENVELOPE', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'MEDIUM', typicalLetterGainMin: 0, typicalLetterGainMax: 1 },
  { guid: 'measure-roof-insulation', code: 'roof_insulation', title: 'Aislar cubierta', category: 'ENVELOPE', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'MEDIUM', typicalLetterGainMin: 0, typicalLetterGainMax: 1 },
  { guid: 'measure-facade-insulation', code: 'facade_insulation', title: 'Aislar fachada', category: 'ENVELOPE', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'HIGH', typicalLetterGainMin: 1, typicalLetterGainMax: 2 },
  { guid: 'measure-terrace-waterproofing', code: 'terrace_waterproofing', title: 'Mejorar terraza', category: 'ENVELOPE', impactArea: 'RISK', defaultPriority: 'OPTIONAL', complexity: 'LOW' },
  { guid: 'measure-heat-pump-air-air', code: 'install_heat_pump_air_air', title: 'Bomba de calor aire-aire', category: 'HVAC', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'MEDIUM', typicalLetterGainMin: 1, typicalLetterGainMax: 2 },
  { guid: 'measure-heat-pump-air-water', code: 'install_heat_pump_air_water', title: 'Aerotermia aire-agua', category: 'HVAC', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'HIGH', typicalLetterGainMin: 1, typicalLetterGainMax: 2 },
  { guid: 'measure-heat-pump-geothermal', code: 'install_heat_pump_geothermal', title: 'Geotermia', category: 'HVAC', impactArea: 'ENERGY_SCORE', defaultPriority: 'LONG_TERM', complexity: 'HIGH', typicalLetterGainMin: 1, typicalLetterGainMax: 3 },
  { guid: 'measure-hybrid-heat-pump', code: 'install_hybrid_heat_pump', title: 'Bomba de calor híbrida', category: 'HVAC', impactArea: 'ENERGY_SCORE', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM', typicalLetterGainMin: 1, typicalLetterGainMax: 2 },
  { guid: 'measure-install-pv', code: 'install_pv', title: 'Instalar fotovoltaica', category: 'RENEWABLE', impactArea: 'ENERGY_SCORE', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM', typicalLetterGainMin: 0, typicalLetterGainMax: 1 },
  { guid: 'measure-solar-thermal', code: 'install_solar_thermal_acs', title: 'Solar térmica ACS', category: 'ACS', impactArea: 'ENERGY_SCORE', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM' },
  { guid: 'measure-heat-recovery-vent', code: 'install_heat_recovery_ventilation', title: 'Ventilación con recuperación de calor', category: 'VENTILATION', impactArea: 'COMFORT', defaultPriority: 'OPTIONAL', complexity: 'HIGH' },
  { guid: 'measure-electrical-upgrade', code: 'electrical_upgrade', title: 'Actualizar instalación eléctrica', category: 'ELECTRICAL', impactArea: 'RISK', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM' },
  { guid: 'measure-plumbing-upgrade', code: 'plumbing_upgrade', title: 'Actualizar fontanería', category: 'PLUMBING', impactArea: 'MAINTENANCE', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM' },
  { guid: 'measure-bathroom-efficiency', code: 'bathroom_efficiency_reform', title: 'Baño eficiente', category: 'BATHROOM', impactArea: 'COMFORT', defaultPriority: 'OPTIONAL', complexity: 'MEDIUM' },
  { guid: 'measure-local-hvac-lighting', code: 'local_hvac_lighting_upgrade', title: 'HVAC e iluminación local', category: 'LOCAL', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'MEDIUM' },
  { guid: 'measure-community-facade', code: 'community_facade_rehab', title: 'Fachada comunitaria', category: 'COMMUNITY', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'HIGH' },
  { guid: 'measure-community-roof', code: 'community_roof_rehab', title: 'Cubierta comunitaria', category: 'COMMUNITY', impactArea: 'ENERGY_SCORE', defaultPriority: 'RECOMMENDED', complexity: 'HIGH' },
  { guid: 'measure-community-heating', code: 'community_central_heating_upgrade', title: 'Central térmica comunitaria', category: 'COMMUNITY', impactArea: 'ENERGY_SCORE', defaultPriority: 'LONG_TERM', complexity: 'HIGH' },
  { guid: 'measure-deep-retrofit', code: 'deep_energy_retrofit', title: 'Rehabilitación energética profunda', category: 'DEEP_RETROFIT', impactArea: 'ENERGY_SCORE', defaultPriority: 'LONG_TERM', complexity: 'HIGH', typicalLetterGainMin: 3, typicalLetterGainMax: 4 },
];

export const measurePriceMaps: MeasurePriceMapSeed[] = [
  { measureCode: 'replace_windows', priceItemCode: 'ENV_WINDOWS_DOUBLE_GLAZING_M2', quantityFormula: 'window_area_m2' },
  { measureCode: 'roof_insulation', priceItemCode: 'ENV_ROOF_INSULATION_M2', quantityFormula: 'roof_area_m2' },
  { measureCode: 'facade_insulation', priceItemCode: 'ENV_FACADE_INSULATION_M2', quantityFormula: 'facade_area_m2' },
  { measureCode: 'terrace_waterproofing', priceItemCode: 'ENV_TERRACE_WATERPROOFING_M2', quantityFormula: 'terrace_area_m2' },
  { measureCode: 'install_heat_pump_air_air', priceItemCode: 'HVAC_HEAT_PUMP_AIR_AIR_UNIT', quantityFormula: 'heat_pump_unit' },
  { measureCode: 'install_heat_pump_air_water', priceItemCode: 'HVAC_HEAT_PUMP_AIR_WATER_UNIT', quantityFormula: 'heat_pump_unit' },
  { measureCode: 'install_heat_pump_geothermal', priceItemCode: 'HVAC_HEAT_PUMP_GEOTHERMAL_UNIT', quantityFormula: 'heat_pump_unit' },
  { measureCode: 'install_hybrid_heat_pump', priceItemCode: 'HVAC_HYBRID_HEAT_PUMP_UNIT', quantityFormula: 'heat_pump_unit' },
  { measureCode: 'install_pv', priceItemCode: 'REN_PV_BASIC_KWP', quantityFormula: 'kwp_estimated' },
  { measureCode: 'install_solar_thermal_acs', priceItemCode: 'REN_SOLAR_THERMAL_ACS_UNIT', quantityFormula: 'fixed_1' },
  { measureCode: 'install_heat_recovery_ventilation', priceItemCode: 'VENT_HEAT_RECOVERY_UNIT', quantityFormula: 'fixed_1' },
  { measureCode: 'electrical_upgrade', priceItemCode: 'ELEC_RENEWAL_M2', quantityFormula: 'floor_area_m2' },
  { measureCode: 'plumbing_upgrade', priceItemCode: 'PLUMBING_RENEWAL_M2', quantityFormula: 'floor_area_m2' },
  { measureCode: 'bathroom_efficiency_reform', priceItemCode: 'BATHROOM_REFORM_MEDIUM_UNIT', quantityFormula: 'bathroom_unit' },
  { measureCode: 'local_hvac_lighting_upgrade', priceItemCode: 'LOCAL_REFORM_SIMPLE_M2', quantityFormula: 'local_area_m2' },
  { measureCode: 'community_facade_rehab', priceItemCode: 'COMMUNITY_FACADE_REHAB_M2', quantityFormula: 'community_facade_area_m2' },
  { measureCode: 'community_roof_rehab', priceItemCode: 'COMMUNITY_ROOF_REHAB_M2', quantityFormula: 'roof_area_m2' },
  { measureCode: 'community_central_heating_upgrade', priceItemCode: 'HVAC_HEAT_PUMP_AIR_WATER_UNIT', quantityFormula: 'heat_pump_unit', defaultFactor: 2 },
  { measureCode: 'deep_energy_retrofit', priceItemCode: 'DEEP_RETROFIT_MEDIUM_M2', quantityFormula: 'floor_area_m2' },
];
